### ISSUE TITLE
Take census of cables and USB hubs and determine what to purchase

### ISSUE THREAD

**Issue by mcorah** [castacks/multidrone_reconstruction_dummy#114]

**Comment by mcorah** [comment]
Three things come to mind:
* We may need more Anker USB Hubs (@hocherie could I get a model number?)
* @wpridgen-cmu has been looking at purchasing ethernet cables. I am unsure of status
* The gray braided USB cables are quite long. We also have a black braided cable that is more appropriate in length... @hocherie we have discussed a bit. Maybe good to follow up regarding which we should be using?

**Comment by wpridgen-cmu** [comment]
To follow up - the Ethernet cables were passed off successfully. 
If you follow up here with links I will purchase

**Comment by mcorah** [comment]
@wpridgen-cmu I think we have most everything we need regarding cables, except an order for USB cables for the GPS I need to get started with Parker.

**Comment by mcorah** [comment]
@wpridgen-cmu Let's finalize details for GQ7 USB once you are back. However, I'm going to close as this task has largely been addressed.
