### ISSUE TITLE
Fix issue with Tmux not closing with backpack

### ISSUE THREAD

**Issue by mcorah** [castacks/multidrone_reconstruction_dummy#134]

**Comment by mcorah** [comment]
@YifanSu1301 We had some trouble with duplicate tmux sessions when trying to run repeat experiments on the backpack.

We can probably add a few lines to kill existing tmux sessions with a matching name.

Maybe a good issue for @shastro @YifanSu1301 or @mcorah

**Comment by shastro** [comment]
Resolved by [fbc65d7](https://bitbucket.org/castacks/mf_ws/commits/fbc65d7ebb97a6ed101b0bd59f39d9b77f45ae06). 

On new branch `fix_mux` which needs to be merged into develop. (I still cannot directly commit to develop)
