### ISSUE TITLE
Transition drones to 10.3.3.x

### ISSUE THREAD

**Issue by shastro** [castacks/multidrone_reconstruction_dummy#136]
--- From Slack ---
The address is set to 10.3.3.1 (same address space as the radios).
To connect to the internet: Plug the gray router in 2202 into the wan port and set 10.3.3.1 as the gateway. I also had to set dns servers manually (not sure if configured wrong) e.g. 8.8.8.8 and 8.8.4.4 for the Google servers.
Let's transition the drones to 10.3.3.x next week.
------------------

**Comment by mcorah** [comment]
This is largely done. Let's focus on moving to an IP table next #44.
